/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import modelo.ImpactoAmbiental;
import control.Excel;
import control.Pdf;
import java.awt.Color;
import java.awt.Container;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Ana Vega
 * @author Nicolás Carmona Cardona
 * @author Mateo Velasquez 
 * @author Jose D. Gómez
 * @author Daniel Cano
 * @author Juan P. Arango
 */
public class Matriz extends javax.swing.JFrame {
    
    Excel archivoCsv;
    Pdf pdf;
    
    /**
     * Creates new form form
     * @throws java.io.IOException
     */
    public Matriz() throws IOException {
        archivoCsv = new Excel("data/input/dataOptions.csv");
        pdf = new Pdf("Informe Impacto Ambiental ");
        initComponents();
        setLocationRelativeTo(this);
        Container c = this.getContentPane();
        c.setBackground(Color.white);
    }
    
    public ImpactoAmbiental crearImpactoAmbiental(){
        ImpactoAmbiental registro = new ImpactoAmbiental(txtProceso.getText(), txtSede.getText(), txtActividadAsociada.getText(), txtCicloVida.getText(), txtObservaciones.getText(), 
                txtLegislacion.getText(), txtControlOperacional.getText(), txtAccionMejora.getText(), boxSituacion.getSelectedItem().toString(), boxAspectoAmbiental.getSelectedItem().toString(), 
                boxImpactoAmbiental.getSelectedItem().toString(), boxRecursoAfectado.getSelectedItem().toString(), boxTipoImpacto.getSelectedItem().toString(), "", Integer.parseInt(boxAlcance.getSelectedItem().toString()),
                Integer.parseInt(boxProbabilidad.getSelectedItem().toString()), Integer.parseInt(boxDuracion.getSelectedItem().toString()), Integer.parseInt(boxRecuperabilidad.getSelectedItem().toString()), 
                Integer.parseInt(boxMagnitud.getSelectedItem().toString()), Integer.parseInt(boxNormatividad.getSelectedItem().toString()), 0, true, "");
        
        if (boxCumpleNormatividad.getSelectedItem().toString().equalsIgnoreCase("si")) {
            registro.setCumpleNormatividad(true);
        } else {
            registro.setCumpleNormatividad(false);
        }
        registro.calcImportancia();
        registro.calcCalificacion();
        registro.calcValor();
        
        System.out.println(registro.toString());
        
        return registro;
    }

    /**
     * This method is called from within the constructor to initialize the Matriz.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblProceso = new javax.swing.JLabel();
        lblSede = new javax.swing.JLabel();
        lblActividadAsociada = new javax.swing.JLabel();
        lblCicloVida = new javax.swing.JLabel();
        lblSituacion = new javax.swing.JLabel();
        lblAspectoAmbiental = new javax.swing.JLabel();
        lblImpactoAmbiental = new javax.swing.JLabel();
        lblRecursoAfectado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProceso = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtActividadAsociada = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCicloVida = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtSede = new javax.swing.JTextArea();
        boxSituacion = new javax.swing.JComboBox();
        boxAspectoAmbiental = new javax.swing.JComboBox();
        boxImpactoAmbiental = new javax.swing.JComboBox();
        boxRecursoAfectado = new javax.swing.JComboBox();
        lblLogo = new javax.swing.JLabel();
        lblObservacion = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        lblLegislacion = new javax.swing.JLabel();
        lblControl = new javax.swing.JLabel();
        lblAccionesMejora = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtControlOperacional = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtAccionMejora = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtLegislacion = new javax.swing.JTextArea();
        lblValoracionImpactos = new javax.swing.JLabel();
        lblTipoImpacto = new javax.swing.JLabel();
        lblAlcance = new javax.swing.JLabel();
        lblProbabilidad = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblRecuperabilidad = new javax.swing.JLabel();
        lblMagnitud = new javax.swing.JLabel();
        lblNormatividad = new javax.swing.JLabel();
        lblCumpleNormatividad = new javax.swing.JLabel();
        boxTipoImpacto = new javax.swing.JComboBox();
        boxAlcance = new javax.swing.JComboBox();
        boxDuracion = new javax.swing.JComboBox();
        boxRecuperabilidad = new javax.swing.JComboBox();
        boxProbabilidad = new javax.swing.JComboBox();
        boxMagnitud = new javax.swing.JComboBox();
        boxNormatividad = new javax.swing.JComboBox();
        boxCumpleNormatividad = new javax.swing.JComboBox();
        btnAgregarRegistro = new javax.swing.JButton();
        btnCargarExcel = new javax.swing.JButton();
        btnGenerarInforme = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDEAM");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1180, 920));

        lblTitulo.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblTitulo.setText("MATRIZ DE IDENTIFICACIÓN DE ASPECTOS Y VALORACIÓN DE IMPACTOS AMBIENTALES");

        lblProceso.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblProceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProceso.setText("PROCESO");
        lblProceso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblProceso.setIconTextGap(2);
        lblProceso.setOpaque(true);

        lblSede.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblSede.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSede.setText("SEDE");
        lblSede.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSede.setOpaque(true);

        lblActividadAsociada.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblActividadAsociada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActividadAsociada.setText("ACTIVIDAD ASOCIADA AL ASPECTO");
        lblActividadAsociada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblActividadAsociada.setOpaque(true);

        lblCicloVida.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblCicloVida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCicloVida.setText("CICLO DE VIDA DEL SERVICIO");
        lblCicloVida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCicloVida.setOpaque(true);

        lblSituacion.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblSituacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSituacion.setText("SITUACIÓN");
        lblSituacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSituacion.setIconTextGap(2);
        lblSituacion.setOpaque(true);

        lblAspectoAmbiental.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblAspectoAmbiental.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAspectoAmbiental.setText("ASPECTO AMBIENTAL ASOCIADO");
        lblAspectoAmbiental.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAspectoAmbiental.setOpaque(true);

        lblImpactoAmbiental.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblImpactoAmbiental.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImpactoAmbiental.setText("IMPACTO AMBIENTAL");
        lblImpactoAmbiental.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImpactoAmbiental.setOpaque(true);

        lblRecursoAfectado.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblRecursoAfectado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecursoAfectado.setText("RECURSO AFECTADO");
        lblRecursoAfectado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblRecursoAfectado.setOpaque(true);

        txtProceso.setColumns(20);
        txtProceso.setLineWrap(true);
        txtProceso.setRows(5);
        txtProceso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtProceso);

        txtActividadAsociada.setColumns(20);
        txtActividadAsociada.setLineWrap(true);
        txtActividadAsociada.setRows(5);
        txtActividadAsociada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(txtActividadAsociada);

        txtCicloVida.setColumns(20);
        txtCicloVida.setLineWrap(true);
        txtCicloVida.setRows(5);
        txtCicloVida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(txtCicloVida);

        txtSede.setColumns(20);
        txtSede.setLineWrap(true);
        txtSede.setRows(5);
        txtSede.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane5.setViewportView(txtSede);

        boxSituacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NORMAL", "ANORMAL", "EMERGENCIA" }));
        boxSituacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boxAspectoAmbiental.setModel(new javax.swing.DefaultComboBoxModel(archivoCsv.getOpcionesAspectoAmbiental()));
        boxAspectoAmbiental.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boxImpactoAmbiental.setModel(new javax.swing.DefaultComboBoxModel(archivoCsv.getOpcionesImpactoAmbiental()));
        boxImpactoAmbiental.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boxRecursoAfectado.setModel(new javax.swing.DefaultComboBoxModel(archivoCsv.getOpcionesRecursoAfectado()));
        boxRecursoAfectado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_IDEAM 1.png"))); // NOI18N

        lblObservacion.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblObservacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObservacion.setText("OBSERVACIONES");
        lblObservacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblObservacion.setIconTextGap(2);
        lblObservacion.setOpaque(true);

        txtObservaciones.setColumns(20);
        txtObservaciones.setLineWrap(true);
        txtObservaciones.setRows(5);
        txtObservaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane10.setViewportView(txtObservaciones);

        lblLegislacion.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLegislacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLegislacion.setText("LEGISLACIÓN AMB. RELACIONADA");
        lblLegislacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblLegislacion.setOpaque(true);

        lblControl.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblControl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblControl.setText("CONTROL OPERACIONAL");
        lblControl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblControl.setOpaque(true);

        lblAccionesMejora.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblAccionesMejora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccionesMejora.setText("ACCIONES DE MEJORA CTRL. OPER.");
        lblAccionesMejora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAccionesMejora.setOpaque(true);

        txtControlOperacional.setColumns(20);
        txtControlOperacional.setLineWrap(true);
        txtControlOperacional.setRows(5);
        txtControlOperacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane11.setViewportView(txtControlOperacional);

        txtAccionMejora.setColumns(20);
        txtAccionMejora.setLineWrap(true);
        txtAccionMejora.setRows(5);
        txtAccionMejora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane12.setViewportView(txtAccionMejora);

        txtLegislacion.setColumns(20);
        txtLegislacion.setLineWrap(true);
        txtLegislacion.setRows(5);
        txtLegislacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane13.setViewportView(txtLegislacion);

        lblValoracionImpactos.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblValoracionImpactos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValoracionImpactos.setText("VALORACIÓN DE IMPACTOS AMBIENTALES");
        lblValoracionImpactos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblValoracionImpactos.setOpaque(true);

        lblTipoImpacto.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblTipoImpacto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoImpacto.setText("TIPO IMPACTO");
        lblTipoImpacto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTipoImpacto.setOpaque(true);

        lblAlcance.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblAlcance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlcance.setText("ALCANCE");
        lblAlcance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAlcance.setOpaque(true);

        lblProbabilidad.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblProbabilidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProbabilidad.setText("PROBABILIDAD");
        lblProbabilidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblProbabilidad.setOpaque(true);

        lblDuracion.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblDuracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDuracion.setText("DURACIÓN");
        lblDuracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDuracion.setOpaque(true);

        lblRecuperabilidad.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblRecuperabilidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecuperabilidad.setText("RECUPERABILIDAD");
        lblRecuperabilidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblRecuperabilidad.setOpaque(true);

        lblMagnitud.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblMagnitud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMagnitud.setText("MAGNITUD");
        lblMagnitud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMagnitud.setOpaque(true);

        lblNormatividad.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblNormatividad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNormatividad.setText("NORMATIVIDAD");
        lblNormatividad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNormatividad.setOpaque(true);

        lblCumpleNormatividad.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblCumpleNormatividad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCumpleNormatividad.setText("<html><body><center>CUMPLE <br>NORMATIVIDAD</center></body></html>");
        lblCumpleNormatividad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCumpleNormatividad.setOpaque(true);

        boxTipoImpacto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POSITIVO (+)", "NEGATIVO (-)" }));
        boxTipoImpacto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boxAlcance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "5", "10" }));
        boxAlcance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boxDuracion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "5", "10" }));
        boxDuracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boxRecuperabilidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "5", "10" }));
        boxRecuperabilidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boxProbabilidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "5", "10" }));
        boxProbabilidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boxMagnitud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "5", "10" }));
        boxMagnitud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boxNormatividad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "10" }));
        boxNormatividad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boxCumpleNormatividad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));
        boxCumpleNormatividad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAgregarRegistro.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarRegistro.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        btnAgregarRegistro.setText("AGREGAR REGISTRO FOTOGRÁFICO");
        btnAgregarRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnAgregarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRegistroActionPerformed(evt);
            }
        });

        btnCargarExcel.setBackground(new java.awt.Color(204, 204, 204));
        btnCargarExcel.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        btnCargarExcel.setText("CARGAR ARCHIVO DE EXCEL");
        btnCargarExcel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnCargarExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCargarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarExcelActionPerformed(evt);
            }
        });

        btnGenerarInforme.setBackground(new java.awt.Color(153, 153, 153));
        btnGenerarInforme.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        btnGenerarInforme.setText("GENERAR INFORME FINAL");
        btnGenerarInforme.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnGenerarInforme.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGenerarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarInformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(lblLogo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblSede, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblActividadAsociada, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblCicloVida, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblAspectoAmbiental, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblImpactoAmbiental, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblRecursoAfectado, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boxSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(boxAspectoAmbiental, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(boxImpactoAmbiental, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(boxRecursoAfectado, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblLegislacion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblControl, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblAccionesMejora, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boxTipoImpacto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxAlcance, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxRecuperabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxMagnitud, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxNormatividad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxCumpleNormatividad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblValoracionImpactos, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTipoImpacto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblAlcance, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblRecuperabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblMagnitud, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblNormatividad, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblCumpleNormatividad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(btnCargarExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(btnAgregarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGenerarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(408, 408, 408))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSede, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActividadAsociada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCicloVida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAspectoAmbiental, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImpactoAmbiental, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecursoAfectado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxAspectoAmbiental, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxImpactoAmbiental, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxRecursoAfectado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLegislacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblControl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccionesMejora, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValoracionImpactos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoImpacto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlcance, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRecuperabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMagnitud, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNormatividad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblCumpleNormatividad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxTipoImpacto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boxAlcance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boxProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boxDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boxMagnitud, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boxRecuperabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boxNormatividad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxCumpleNormatividad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarExcel)
                    .addComponent(btnAgregarRegistro))
                .addGap(22, 22, 22)
                .addComponent(btnGenerarInforme)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarRegistroActionPerformed

    private void btnCargarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarExcelActionPerformed

    private void btnGenerarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarInformeActionPerformed
        ImpactoAmbiental registroAmbiental = crearImpactoAmbiental();
        pdf.crearReporte(registroAmbiental);
        //archivoCsv.ExportarCSV(new List<>);
    }//GEN-LAST:event_btnGenerarInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the Matriz */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Matriz().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Matriz.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxAlcance;
    private javax.swing.JComboBox boxAspectoAmbiental;
    private javax.swing.JComboBox boxCumpleNormatividad;
    private javax.swing.JComboBox boxDuracion;
    private javax.swing.JComboBox boxImpactoAmbiental;
    private javax.swing.JComboBox boxMagnitud;
    private javax.swing.JComboBox boxNormatividad;
    private javax.swing.JComboBox boxProbabilidad;
    private javax.swing.JComboBox boxRecuperabilidad;
    private javax.swing.JComboBox boxRecursoAfectado;
    private javax.swing.JComboBox boxSituacion;
    private javax.swing.JComboBox boxTipoImpacto;
    private javax.swing.JButton btnAgregarRegistro;
    private javax.swing.JButton btnCargarExcel;
    private javax.swing.JButton btnGenerarInforme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAccionesMejora;
    private javax.swing.JLabel lblActividadAsociada;
    private javax.swing.JLabel lblAlcance;
    private javax.swing.JLabel lblAspectoAmbiental;
    private javax.swing.JLabel lblCicloVida;
    private javax.swing.JLabel lblControl;
    private javax.swing.JLabel lblCumpleNormatividad;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblImpactoAmbiental;
    private javax.swing.JLabel lblLegislacion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMagnitud;
    private javax.swing.JLabel lblNormatividad;
    private javax.swing.JLabel lblObservacion;
    private javax.swing.JLabel lblProbabilidad;
    private javax.swing.JLabel lblProceso;
    private javax.swing.JLabel lblRecuperabilidad;
    private javax.swing.JLabel lblRecursoAfectado;
    private javax.swing.JLabel lblSede;
    private javax.swing.JLabel lblSituacion;
    private javax.swing.JLabel lblTipoImpacto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValoracionImpactos;
    public javax.swing.JTextArea txtAccionMejora;
    public javax.swing.JTextArea txtActividadAsociada;
    public javax.swing.JTextArea txtCicloVida;
    public javax.swing.JTextArea txtControlOperacional;
    public javax.swing.JTextArea txtLegislacion;
    public javax.swing.JTextArea txtObservaciones;
    public javax.swing.JTextArea txtProceso;
    public javax.swing.JTextArea txtSede;
    // End of variables declaration//GEN-END:variables
}
